/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import conexiones.UserLogin;
import conexiones.usuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Login extends javax.swing.JFrame {

	/**
	 * Creates new form Login
	 */
	public Login() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tb_loginUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tb_loginPass = new javax.swing.JPasswordField();
        btn_ingresar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesión");
        setLocation(new java.awt.Point(510, 240));
        getContentPane().setLayout(null);
        getContentPane().add(tb_loginUsuario);
        tb_loginUsuario.setBounds(200, 110, 160, 22);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 80, 0);

        jLabel2.setText("PASSWORD");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 160, 90, 16);
        getContentPane().add(tb_loginPass);
        tb_loginPass.setBounds(200, 150, 160, 22);

        btn_ingresar.setText("Login");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ingresar);
        btn_ingresar.setBounds(350, 240, 63, 25);

        jLabel3.setText("USER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 120, 80, 10);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
		UserLogin modSQL = new UserLogin();
		usuarios mod = new usuarios();
		String pass = new String(tb_loginPass.getPassword());
		
		if(!tb_loginUsuario.getText().equals("") && !pass.equals("")){
			mod.setUsuario(tb_loginUsuario.getText());
			mod.setPassword(pass);
			
			if(modSQL.login(mod)){
				//JOptionPane.showMessageDialog(null, "Datos correctos");
				dispose();
				frmMiCRUD iniciar = new frmMiCRUD();
				iniciar.setVisible(true);
			} else{
				JOptionPane.showMessageDialog(null, "Datos incorrectos");
			}	
		} else{
			JOptionPane.showMessageDialog(null, "Debe ingresar sus datos");
		}
    }//GEN-LAST:event_btn_ingresarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField tb_loginPass;
    private javax.swing.JTextField tb_loginUsuario;
    // End of variables declaration//GEN-END:variables
}
